fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "user@uga.edu"
    sender_name: "user@uga.edu"
  service:
    mailer: fos_user.mailer.twig_swift