p_rayno_cas_auth:
    server_login_url: https://sso.uga.edu/cas/login
    server_validation_url: https://sso.uga.edu/cas/serviceValidate
    server_logout_url: https://sso.uga.edu/cas/logout
    xml_namespace: cas