p_rayno_cas_auth:
    server_login_url: https://cas.stage.uga.edu/cas/login
    server_validation_url: https://cas.stage.uga.edu/cas/login
    server_logout_url: https://cas.stage.uga.edu/cas/login
    xml_namespace: cas
#    options:[] see http://docs.guzzlephp.org/en/latest/request-options.html
