login:
    path: /login
    controller: App\Controller\CourseController::upper
    defaults:
      area: "U"
      term: "current"

logout:
    path: /logout
    controller: App\Controller\CourseController::upper
    defaults:
      area: "U"
      term: "current"

login_check:
    path: /login_check
