#login:
#    path: /login
#    defaults: { _controller: 'App\Controller\CourseController::index' }
#
#logout:
#    path: /logout
#    defaults: { _controller: 'App\Controller\CourseController::index' }
#
#login_check:
#    path: /login_check
