security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            provider: fos_userbundle
            logout:       true
            anonymous:    true
            logout_on_user_change: true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_USER }
        - { path: edit$, role: ROLE_EDITOR }
        - { path: new$, role: ROLE_EDITOR }
        - { path: delete$, role: ROLE_EDITOR }
        - { path: create$, role: ROLE_EDITOR }
        - { path: update$, role: ROLE_EDITOR }