security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        cas:
            id: App\Service\CertUserProvider

    firewalls:
        main:
            anonymous: ~

            guard:
                authenticators:
                    - prayno.cas_authenticator
            logout:
                path: /logout
                success_handler: PRayno\CasAuthBundle\Event\LogoutSuccessHandler

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_USER }
        - { path: edit$, role: ROLE_EDITOR }
        - { path: new$, role: ROLE_EDITOR }
        - { path: delete$, role: ROLE_EDITOR }
        - { path: create$, role: ROLE_EDITOR }
        - { path: update$, role: ROLE_EDITOR }